# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ developer, release* ]
  pull_request:
    branches: [ developer ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Command Line
      run: javac -classpath src/. src/*.java src/models/*.java src/dao/*.java  src/views/*.java src/controllers/*.java

  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'release')
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref}}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          ${{ github.event.commits[0].message }}
        draft: false
        prerelease: false                             
